apiVersion: v1
kind: Service
metadata:
  name: warp
  namespace: lae-production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: warp
